artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_dir: digit_reco.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/data




data_transformation: 
  root_dir: artifacts/data_transformation
  input_data_file: artifacts/data_ingestion/data/train.csv
  output_data_file: artifacts/data_transformation
  training_dir: artifacts/data_transformation/training
  valid_dir: artifacts/data_transformation/validation


model_traning :
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5